spring:
  application:
    name: Web Application Backend
  profiles:
    active: dev
  security:
    jwt:
      secret: "supersecureverylongrandomsecretkeythatis32byteslong"
      #      secret: ${JWT_SECRET}
      expiration: 3600000 # 1 hour
